# Generated by Django 4.1.2 on 2022-12-29 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0002_auction_bid_comment_watchlist_winner"),
    ]

    operations = [
        migrations.AddField(
            model_name="auction",
            name="active",
            field=models.BooleanField(default=True),
        ),
    ]
